# Artificial Neural Network

### Importing the libraries

In [33]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [34]:
tf.__version__

'2.4.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [35]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [36]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [37]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [38]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform((X)[:, 2])

In [39]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [40]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#[0] refers to the country column
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [41]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,
                    random_state = 0)

### Feature Scaling

In [43]:
#always necessary for ANN
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [44]:
#'ann' will be the artificial neural network
#it is a sequence of layers
#'tf' and 'keras' is the library, 
#we have the 'models' module
#we have the class 'Sequential'
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [45]:
#here we apply the 'add()' method
#the number of neurons in the input layer is already
#defined by column numbers of dataset/ matrix array
#'units' is the number of neurons in the first hidden layer
#'activation' is our rectifier activation function
#activation function decides whether a neuron should be activated or not
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [46]:
#same line as above
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [47]:
#here we only have one output neuron
#the activation function will be sigmoid, because that also
#gives us the probability of the churn
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [48]:
#choose optimizer: adjusts the weights through stochastic gradient descent
#choose loss function (difference between predicted and actual value)
#choose metric (like accuracy)
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

### Training the ANN on the Training set

In [49]:
#batch_size: number of predicted results, that will be compared
#to real results in one step 
#epoch: one training cycle, in which all results will be compared 
#to all real results
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 953us/step - loss: 0.7201 - accuracy: 0.5447
Epoch 2/100
250/250 [==============================] - 0s 979us/step - loss: 0.5303 - accuracy: 0.7912
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4766 - accuracy: 0.8043
Epoch 4/100
250/250 [==============================] - 0s 963us/step - loss: 0.4386 - accuracy: 0.8096
Epoch 5/100
250/250 [==============================] - 0s 946us/step - loss: 0.4053 - accuracy: 0.8244
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3982 - accuracy: 0.8260
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3961 - accuracy: 0.8335
Epoch 8/100
250/250 [==============================] - 0s 947us/step - loss: 0.3760 - accuracy: 0.8425
Epoch 9/100
250/250 [==============================] - 0s 993us/step - loss: 0.3810 - accuracy: 0.8414
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [50]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [51]:
#predict a result
print(ann.predict(sc.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 
                60000, 2.0, 1, 1, 50000]])))

[[0.02920499]]


In [52]:
#change the probability into a 'TrueE' or 'False'
#we can also adjust the threshold if necessary
print(ann.predict(sc.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 
              60000, 2.0, 1, 1, 50000]])) > 0.5)

[[False]]


**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [55]:
y_pred = ann.predict(X_test)

there are 2 ways to transform array of probabilities into boolean array

In [74]:
new1_y_pred = (y_pred > 0.5)

In [75]:
new1_y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [70]:
new_y_pred = np.where(y_pred > 0.5, 1, 0)

In [71]:
new_y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

### Making the Confusion Matrix

In [76]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, new1_y_pred)
print(cm)
accuracy_score(y_test, new1_y_pred)

[[1520   75]
 [ 203  202]]


0.861

**make an ANN on regression**