In [55]:
#import libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [56]:
#import dataset
dataset = pd.read_excel('dataset.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [57]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [58]:
#split dataset in train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [59]:
#initialize the ANN as a sequence of layers
#'ann' is an object of the 'Sequential' class
ann = tf.keras.models.Sequential()

In [60]:
#add input layer
#'Dense' stands for full connection between input and first hidden layer
#'units' are neurons in first hidden layer
#'relu' stands for rectifier function
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))
#add second hidden layer
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

In [61]:
#add output layer
#for regression problems, no activation function required
ann.add(tf.keras.layers.Dense(units=1))

In [62]:
#compiling the ANN
#that means: connect to ANN, optimizer and loss function
#optimizer: stochastic gradient descent tool (to adjust weights)
#loss function: gets difference between actual and predicted value
ann.compile(optimizer='adam', loss='mean_squared_error')

In [63]:
#train ANN on training set
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 921us/step - loss: 162865.9179
Epoch 2/100
240/240 [==============================] - 0s 904us/step - loss: 8165.2155
Epoch 3/100
240/240 [==============================] - 0s 908us/step - loss: 406.9686
Epoch 4/100
240/240 [==============================] - 0s 929us/step - loss: 376.1240
Epoch 5/100
240/240 [==============================] - 0s 952us/step - loss: 329.7097
Epoch 6/100
240/240 [==============================] - 0s 953us/step - loss: 277.4702
Epoch 7/100
240/240 [==============================] - 0s 934us/step - loss: 241.3462
Epoch 8/100
240/240 [==============================] - 0s 983us/step - loss: 190.2795
Epoch 9/100
240/240 [==============================] - 0s 998us/step - loss: 164.8440
Epoch 10/100
240/240 [==============================] - 0s 991us/step - loss: 128.5113
Epoch 11/100
240/240 [==============================] - 0s 938us/step - loss: 107.7498
Epoch 12/100
240/240 [==========================

In [64]:
#predict results of test set
y_pred = ann.predict(X_test)

In [65]:
y_pred[:5]

array([[432.7 ],
       [463.78],
       [467.3 ],
       [450.36],
       [461.58]], dtype=float32)

In [66]:
#compare predicted values with real values
#'precision' means digits after the comma
np.set_printoptions(precision=2)

#we have to transform the horizontal vectors 
#'y_pred' and 'y_test' into a vertical ones
#this is done with reshape

#then we want to put the 2 vectors next to each other
#done with concatenate
#concatenate has 2 arguments
#First argument: the 2 vectors y_pred & y_test
#Second argument: a '1', that stands for vertical concatenation
#(if we want horizontal concatenation: it should be 0)
conc_vec = np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1)
conc_vec 

array([[432.7 , 431.23],
       [463.78, 460.01],
       [467.3 , 461.14],
       ...,
       [474.53, 473.26],
       [441.21, 438.  ],
       [460.47, 463.28]])

In [67]:
#get mean squared error from predicted values
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

26.544347164386934